services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portal_cautivo_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - portal_network

  mysql:
    image: mysql:8.4
    container_name: portal_cautivo_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: portal_cautivo
      MYSQL_USER: portal_user
      MYSQL_PASSWORD: portal_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -proot_password --silent"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - portal_network

  radius:
    build:
      context: ./docker/freeradius
      dockerfile: Dockerfile
    container_name: portal_cautivo_radius

    command:
      - "-X"

    environment:
      RADIUS_API_TOKEN: ${RADIUS_API_TOKEN}
      RADIUS_SHARED_SECRET: ${RADIUS_SHARED_SECRET}

    ports:
      - "192.168.56.1:1812:1812/udp"
      - "192.168.56.1:1813:1813/udp"

    depends_on:
      - app

    networks:
      - portal_network

volumes:
  mysql_data:

networks:
  portal_network:
    driver: bridge